name: example-golang-ci

on:
  push:
    branches: [ main, ci-test ]
  pull_request:
    branches: [ main, ci-test ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    - uses: docker-practice/actions-setup-docker@master
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Starter Docker Test
      run: docker run -d -p 127.0.0.1:4000:4000 pingcap/tidb:v5.1.0
          
    - name: Set MySQL Client
      run: sudo apt install mysql-client -y
      
    - name: Test
      run: mysql --host 127.0.0.1 --port 4000 -u root -e "SELECT VERSION()"
