name: example-golang-ci

on:
  push:
    branches: [ main, ci-test ]
  pull_request:
    branches: [ main, ci-test ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Set up TiUP
      run: curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
      
    - name: Set up TiDB
      run: nohup tiup playground &
      
    - name: Test
      run: make test
